import type { Metadata } from "next";
import { ContentLayout } from "@/components/ContentLayout";

export const metadata: Metadata = {
  title: "Terms of Use — cite2fn",
};

export default function Terms() {
  return (
    <ContentLayout title="Terms of Use">
      <div className="rounded-md border border-amber-300 bg-amber-50 px-4 py-3 text-sm text-amber-900">
        <strong>Draft — please review with counsel.</strong> This is a
        reasonable starting point for a free research tool, but it is not
        legal advice and should be reviewed by a licensed attorney before
        being relied on in any jurisdiction.
      </div>

      <p className="text-xs text-slate-500">Last updated: April 2026.</p>

      <h2 className="mt-8 text-xl font-semibold text-slate-900">
        1. What this service is
      </h2>
      <p>
        cite2fn (the &ldquo;Service&rdquo;) is a free tool that converts
        hyperlinked citations in a Microsoft Word document into formatted
        footnotes, endnotes, or a reference list. By uploading a document you
        agree to these Terms of Use.
      </p>

      <h2 className="mt-8 text-xl font-semibold text-slate-900">
        2. No warranty
      </h2>
      <p>
        The Service is provided &ldquo;as is&rdquo; and &ldquo;as
        available,&rdquo; without warranty of any kind, express or implied,
        including any implied warranty of merchantability, fitness for a
        particular purpose, or non-infringement. Citation formatting is
        generated by software and large language models that make mistakes.
        You are solely responsible for verifying every citation in the
        output before relying on it.
      </p>

      <h2 className="mt-8 text-xl font-semibold text-slate-900">
        3. What you may not upload
      </h2>
      <p>Please do not use the Service to process documents that contain:</p>
      <ul className="list-disc space-y-1 pl-6">
        <li>
          Confidential, privileged, or trade-secret information of any kind
        </li>
        <li>Personal data of third parties without a lawful basis</li>
        <li>Content that infringes someone else&apos;s rights</li>
        <li>Material that is illegal in your jurisdiction</li>
      </ul>
      <p>
        The Service holds files only transiently for processing (see the
        Privacy Policy), but you should treat any upload as if it might be
        readable by a server operator during that window.
      </p>

      <h2 className="mt-8 text-xl font-semibold text-slate-900">
        4. Third-party services
      </h2>
      <p>
        Citation formatting is performed by a third-party language model
        provider — either Anthropic (when you supply your own API key) or
        Groq (for the free fallback). URL metadata is fetched by the Service
        making HTTPS requests to the source servers you linked. Your use of
        those third parties is subject to their own terms.
      </p>

      <h2 className="mt-8 text-xl font-semibold text-slate-900">
        5. Rate limits and availability
      </h2>
      <p>
        The Service may rate-limit or refuse requests to protect availability
        and its underlying providers. We may change or discontinue features
        at any time without notice.
      </p>

      <h2 className="mt-8 text-xl font-semibold text-slate-900">
        6. Limitation of liability
      </h2>
      <p>
        To the maximum extent permitted by law, the Service and its author
        are not liable for any indirect, incidental, special, consequential,
        or punitive damages, or any loss of data, revenue, or profits,
        arising from your use of the Service.
      </p>

      <h2 className="mt-8 text-xl font-semibold text-slate-900">
        7. Governing law
      </h2>
      <p>
        <em>
          [Placeholder — update with your jurisdiction before publishing.]
        </em>{" "}
        These Terms are governed by the laws of your jurisdiction of
        residence.
      </p>

      <h2 className="mt-8 text-xl font-semibold text-slate-900">
        8. Changes to these Terms
      </h2>
      <p>
        We may update these Terms from time to time. The date above reflects
        the most recent update. Continued use after a change constitutes
        acceptance of the new Terms.
      </p>
    </ContentLayout>
  );
}
